Feat: Initial implementation
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -26,20 +26,40 @@ jobs:
       - name: "Checkout repository"
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      # Perform setup prior to running test(s)
-      - name: "Testing setup step"
-        shell: bash
-        run: |
-          # Testing setup step
-          echo "Testing setup step"
-          echo "Testing setup step/summary output" >> "$GITHUB_STEP_SUMMARY"
-
-      - name: "Running local action: ${{ github.repository }}"
+      - name: "Running local action: ${{ github.repository }} 25.02.3"
         uses: ./
+        with:
+          string: "25.02.3"
 
-      - name: "Validating local action: ${{ github.repository }}"
+      - name: "Running local action: ${{ github.repository }} 2025.02.3"
+        uses: ./
+        with:
+          string: "2025.02.3"
+
+      - name: "Running local action: ${{ github.repository }} v2025.02.3-dev1"
+        uses: ./
+        with:
+          string: "v2025.02.3-dev1"
+
+      # yamllint disable-line rule:line-length
+      - name: "Running local action: ${{ github.repository }} v1.not-valid.3.garbage [NOT CalVer]"
+        uses: ./
+        with:
+          string: "v1.not-valid.3.garbage"
+
+      # yamllint disable-line rule:line-length
+      - name: "Running local action: ${{ github.repository }} [Override Failure]"
+        uses: ./
+        id: failure
+        continue-on-error: true
+        with:
+          string: "v1.not-valid.3.garbage"
+          exit_on_fail: true
+
+      - name: "Error if step above did NOT fail"
+        if: steps.failure.outcome == 'success'
         shell: bash
         run: |
-          # Local action validation
-          echo "Validating local action: ${{ github.repository }}"
-          echo "Validation step summary output" >> "$GITHUB_STEP_SUMMARY"
+          # Error if step above did NOT fail
+          echo "Error: previous test step did NOT fail ❌"
+          exit 1
diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -2,38 +2,65 @@
 # SPDX-License-Identifier: Apache-2.0
 # SPDX-FileCopyrightText: 2025 The Linux Foundation
 
-# actions-template
-name: "🛠️ Actions Template"
-description: "Description of action"
-# Any relevant notes/observations can go here
+# tag-validate-calver-action
+name: '🏷️ Check Calendar Versioning String/Tag'
+description: 'Validates a given string for conformity to Calendar Versioning'
 
 inputs:
-  INPUT:
-    description: "Description of input"
+  # Mandatory
+  string:
+    description: 'Tag/version string to check/verify'
+    type: 'string'
+    required: true
+  exit_on_fail:
+    description: 'Exits with error status if CalVer check fails'
+    type: 'boolean'
     required: false
-    type: string
-    default: "input"
+    default: false
 
 outputs:
-  OUTPUT:
-    description: "Description of output"
-    value: ${{ steps.code.outputs.output }}
+  # Mandatory
+  valid:
+    description: 'Set true if tag passes semantic versioning check'
+    value: ${{ steps.validate.outputs.valid }}
 
 runs:
-  using: "composite"
+  using: 'composite'
   steps:
-    - name: "Friendly Name"
-      id: code
+    - name: 'Validate string/tag: CalVer'
+      id: validate
       shell: bash
+      # yamllint disable rule:line-length
       run: |
-        # Friendly Name
-        INPUT="${{ inputs.input }}"
-        if [ -z "$INPUT" ]; then
-          echo "Error: mandatory input INPUT was not set/configured ❌"
+        # Validate string/tag: CalVer
+        string=${{ inputs.string }}
+        exit_on_fail="${{ inputs.exit_on_fail }}"
+        if [ -z "$string" ]; then
+          echo "Error: input string was not populated ❌"
           exit 1
         fi
 
-        echo "output=$INPUT" >> "$GITHUB_ENV"
-        echo "output=$INPUT" >> "$GITHUB_OUTPUT"
-        echo "Action received a valid input: $INPUT ✅"
-        echo "Action received a valid input: $INPUT ✅" >> "$GITHUB_STEP_SUMMARY"
+        echo "String to check: $string"
+        # Strip leading "v" character if present
+        if [[ "$string" == v* ]] || [[ "$string" == V* ]]; then
+          string="${string:1}"
+        fi
+
+        # See: https://regex101.com/r/BQfFYn/1
+        # Best effort at a reasonable RegEx that accepts a number of variations
+        pattern="^(\d{2}|\d{4}).(\d{1}|\d{2})(\.(\d{1}|\d{2})?((\.|\-|\_))[a-zA-Z0-9].*)$"
+
+        # Use grep with PCRE regular expression support
+        checked=$(echo $string | grep -P "$pattern" || true)
+        if [ "$checked" = "$string" ]; then
+          echo "Tag/version string is valid CalVer ✅"
+          echo "valid=true" >> $GITHUB_ENV
+          echo "valid=true" >> $GITHUB_OUTPUT
+        else
+          echo "Tag/version string is NOT valid CalVer ❌"
+          echo "valid=false" >> $GITHUB_ENV
+          echo "valid=false" >> $GITHUB_OUTPUT
+          if [ "f$exit_on_fail" = "ftrue" ]; then
+            exit 1
+          fi
+        fi
